trigger: none
parameters: 
  - name: deployInfra
    displayName: Deploy New Infrastructure
    type: boolean
    default: false
  - name: deployApp
    displayName: Deploy Application
    type: boolean
    default: false
variables:
  - name: deployInfra
    value: ${{ eq(parameters.deployInfra, true) }}
  - name: deployApp
    value: ${{ eq(parameters.deployApp, true) }}

pool:
  name: Linux-sh-pool

stages:
  #- template: pre-steps.yaml
  - template: env.yaml
    parameters: 
     environments:
     #DigiGeld PROD
     - name: DigiGeld
       code: prod
       azureSubscription: DigiGeld SC PROD
       resource_group: dg-rg-prod1
       location: North Europe
       acr_name: dgrgprod1
       cluster_name: dg-aks-prod1
     #DigiGeld ACC
     - name: DigiGeld
       code: acc
       azureSubscription: DigiGeld SC ACC
       resource_group: dg-rg-acc
       location: North Europe
       acr_name: dgacracc
       cluster_name: dg-aks-acc
