parameters:
  - name: azureSubscription
    type: string
    default: 'your-azure-subscription-id'
  - name: resource_group
    type: string
    default: 'your-resource-group-name'
  - name: location
    type: string
    default: 'northeurope'
  - name: acr_name
    type: string
    default: 'your-acr-name'
  - name: cluster_name
    type: string
    default: 'your-cluster-name'
  - name: node_count
    type: int
    default: 3
  - name: vm_size
    type: string
    default: 'Standard_DS2_v2'

jobs:
  - deployment: deployEnvironment
    displayName: Deploy Environment
    timeoutInMinutes: 250
    strategy:
      runOnce:
        deploy:
          steps:
            # Deploy Infrastructure
            - task: AzureCLI@2
              condition: eq(variables['deployInfra'], 'true')
              displayName: Deploying Infrastructure
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptPath: 'scripts/deploy-infra.sh'
                arguments: >
                  ${{ parameters.resource_group }}
                  ${{ parameters.location }}
                  ${{ parameters.acr_name }}
                  ${{ parameters.cluster_name }}
                  ${{ parameters.node_count }}
                  ${{ parameters.vm_size }}

            ##Deploy Ghost Image
            #  - task: AzurePowerShell@5
            #    condition: eq(variables['deployApp'], 'true')
            #    displayName: Deploying Image
            #    inputs:
            #    azureSubscription:
            #    ScriptPath:
            #    ScriptArguments:
            #    AzurePowershellVersion: LatestVersion
            #    pwsh: true
            ##Test deployment
            #- task: AzurePowerShell@5
            #    condition: eq(variables['deployApp'], 'true')
            #    displayName: Testing deployment 
            #    inputs:
            #    azureSubscription:
            #    ScriptPath:
            #    ScriptArguments:
            #    AzurePowershellVersion: LatestVersion
            #    pwsh: true
            ##Deploy security and monitoring
            #- task: AzurePowerShell@5
            #    condition: eq(variables['deployApp'], 'true')
            #    displayName: Deploying Security and Monitoring
            #    inputs:
            #    azureSubscription:
            #    ScriptPath:
            #    ScriptArguments:
            #    AzurePowershellVersion: LatestVersion
            #    pwsh: true
            