trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnection: 'DigiGeld SC'
  location: 'northeurope'
  resourceGroupName: 'dg-rg-prod'
  templateFile: 'template\infra.bicep'

stages:
  - stage: Deploy
    jobs:
      - job: DeployInfrastructure
        displayName: 'Deploy AKS, Cosmos DB, and Front Door'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Check if the resource group exists
                if ! az group exists --name $(resourceGroupName); then
                  echo "Resource group $(resourceGroupName) does not exist. Creating..."
                  az group create --name $(resourceGroupName) --location $(location)
                else
                  echo "Resource group $(resourceGroupName) already exists."
                fi

                # Deploy the Bicep template to the resource group
                az bicep install
                az deployment group create \
                  --resource-group $(resourceGroupName) \
                  --template-file $(templateFile) \
                  --parameters location=$(location) \
                    aksClusterName=myAKSCluster \
                    cosmosDbAccountName=myCosmosDBAccount \
                    frontDoorName=myFrontDoor
            displayName: 'Deploy Resources with Bicep'
