parameters:
 - name: resource_group
   type: string
 - name: location
   type: string
 - name: acr_name
   type: string

jobs:
  - deployment: deployEnvironment
    displayNanme: Deploy Environment
    timeoutInMinutes: 250
    strategy:
      runOnce:
        deploy:
           steps: none
            #Deploy infra
            #Deploy Image
            #Test deployment
            #Deploy security
            