stages:
- stage: build
  displayName: Preparation steps
  jobs:
  - job: BuildJob
    displayName: Preparation Job
    variables:
      Build.ArtifactStagingDirectory: $(Pipeline.Workspace)/staging
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.SourcesDirectory)
        TargetFolder: $(Build.ArtifactStagingDirectory)/s
    -publish: $(Build.ArtifactStagingDirectory)
      artifact: artifacts