stages:
- stage: build
  displayName: Preparation steps
  jobs:
  - job: artifacts
    displayName: Copy files and publish artifact
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.SourcesDirectory)
        TargetFolder: $(Build.ArtifactStagingDirectory)/s
