parameters:
  - name: azureSubscription
    type: string
    default: 'your-azure-subscription-id'
  - name: resource_group
    type: string
    default: 'your-resource-group-name'
  - name: location
    type: string
    default: 'northeurope'
  - name: acr_name
    type: string
    default: 'your-acr-name'
  - name: cluster_name
    type: string
    default: 'your-cluster-name'
  - name: build_id
    type: string
    default: 'latest'

jobs:
  - deployment: deployEnvironment
    displayName: Deploy Environment
    environment: none
    timeoutInMinutes: 250
    strategy:
      runOnce:
        deploy:
          steps:
            # Deploying Infrastructure Components.
            - task: AzurePowerShell@5
              condition: eq(variables['deployInfra'], 'true')
              displayName: 'Deploying Infrastructure Components.'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }} # Replace with your Azure service connection
                ScriptType: 'InlineScript'
                Inline: |
                    Import-Module '$(Pipeline.Workspace)/artifacts/modules/ghost.psm1'
                    NewDeployInfra -resourceGroupName ${{ parameters.resource_group }} -Location ${{ parameters.location }} -aksClusterName ${{ parameters.cluster_name }} -acrName ${{ parameters.acr_name }} -basepath "$(Pipeline.Workspace)/artifacts/Ghost/templates/bicep"
                azurePowerShellVersion: 'LatestVersion'
            # Deploying App: ghost-deployment.yaml file customize.
            - task: PowerShell@2
              condition: eq(variables['deployApp'], 'true')
              displayName: "Deploying App: ghost-deployment.yaml file customize."
              inputs:
                ScriptType: 'InlineScript'
                Inline: |
                  Import-Module '$(Pipeline.Workspace)/artifacts/modules/deploy-infra.psm1'
                  Setup-Ghost-Files -filepath "$(Pipeline.Workspace)/artifacts/Ghost/templates/yaml/ghost-deployment.yaml" -filefinalpath "$(Pipeline.Workspace)/artifacts/Ghost/templates/yaml/${{ parameters.cluster_name }}.yaml" -image "${{parameters.acr_name}}.azurecr.io/ghost-app:${{parameters.build_id}}"
                pwsh: true
            # Deploying App: Push Ghost Image to AKS.
            - task: Bash@3
              condition: eq(variables['deployApp'], 'true')
              displayName: "Deploying App: Push Ghost Image to AKS."
              inputs:
                filePath: '$(Pipeline.Workspace)/artifacts/Ghost/scripts/bash/ghost-deployment.sh'
                arguments: >
                  ${{ parameters.resource_group }}
                  ${{ parameters.cluster_name }}
                  "$(Pipeline.Workspace)/artifacts/Ghost/templates/yaml/${{ parameters.cluster_name }}.yaml"
                  "$(Pipeline.Workspace)/artifacts/Ghost/templates/yaml/monitoring-deploy.yaml"