parameters:
  - name: azureSubscription
    type: string
    default: 'your-azure-subscription-id'
  - name: resource_group
    type: string
    default: 'your-resource-group-name'
  - name: location
    type: string
    default: 'northeurope'
  - name: acr_name
    type: string
    default: 'your-acr-name'
  - name: cluster_name
    type: string
    default: 'your-cluster-name'
  - name: build_id
    type: string
    default: 'latest'

jobs:
  - deployment: deployEnvironment
    displayName: Deploy Environment
    environment: none
    timeoutInMinutes: 250
    strategy:
      runOnce:
        deploy:
          steps:
            # Deploy Infrastructure 
            #- task: AzurePowerShell@5
            #  condition: eq(variables['deployInfra'], 'true')
            #  displayName: "Deploying Infrastructure: Pre-requisites"
            #  inputs:
            #    azureSubscription: ${{ parameters.azureSubscription }}
            #    ScriptPath: '$(Pipeline.Workspace)/artifacts/scripts/deploy-infra.ps1'
            #    ScriptArguments: >
            #      -resourceGroupName ${{ parameters.resource_group }}
            #      -location ${{ parameters.location }}
            #      -acrName ${{ parameters.acr_name }}
            #      -aksClusterName ${{ parameters.cluster_name }}
            #    azurePowerShellVersion: LatestVersion
            #    pwsh: true
            ## Deploy aks cluster
            #- task: Bash@3
            #  condition: eq(variables['deployInfra'], 'true')
            #  displayName: "Deploying Infrastructure: aks cluster"
            #  inputs:
            #    filePath: '$(Pipeline.Workspace)/artifacts/scripts/deploy-aks.sh'
            #    arguments: >
            #      ${{ parameters.resource_group }}
            #      ${{ parameters.acr_name }}
            #      ${{ parameters.cluster_name }}
            #Deploy Keyvault
            - task: AzureCLI@2
              condition: eq(variables['deployInfra'], 'true')
              displayName: 'Create Key Vault and Add Secrets'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}  # Replace with your service connection name
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az keyvault create --name ${{ parameters.cluster_name }} --resource-group ${{ parameters.resource_group }} --location ${{ parameters.location }}
                  az keyvault secret set --vault-name ${{ parameters.cluster_name }}  --name "root-password" --value "xxxssss"
                  az keyvault secret set --vault-name ${{ parameters.cluster_name }}  --name "user" --value "ghostdbuser"
                  az keyvault secret set --vault-name ${{ parameters.cluster_name }}  --name "password" --value "xxxssss"
            # Customize ghost-deployment.yaml file
            - task: PowerShell@2
              condition: eq(variables['deployApp'], 'true')
              displayName: Customizing ghost-deployment.yaml file
              inputs:
                targetType: 'filePath'
                filePath: '$(Pipeline.Workspace)/artifacts/scripts/setup-ghost-file.ps1'
                arguments: >
                  -filepath "$(Pipeline.Workspace)/artifacts/templates/ghost-deployment.yaml" 
                  -filefinalpath "$(Pipeline.Workspace)/artifacts/templates/${{ parameters.cluster_name }}.yaml"
                  -password "xxxsss" 
                  -image "${{parameters.acr_name}}.azurecr.io/ghost-app:${{parameters.build_id}}"
                pwsh: true
            # Deploy Ghost Image
            - task: Bash@3
              condition: eq(variables['deployApp'], 'true')
              displayName: Deploying Ghost Image
              inputs:
                filePath: '$(Pipeline.Workspace)/artifacts/scripts/ghost-deployment.sh'
                arguments: >
                  ${{ parameters.resource_group }}
                  ${{ parameters.cluster_name }}
                  "$(Pipeline.Workspace)/artifacts/templates/${{ parameters.cluster_name }}.yaml"
                  
