trigger: none

parameters: 
  - name: deployInfra
    displayName: Deploy New Infrastructure
    type: boolean
    default: true

  - name: deployApp
    displayName: Deploy Application
    type: boolean
    default: true
  
  - name: build_id
    displayName: Build Id for ACR Image
    type: string
    default: latest
variables:
  - name: deployInfra
    value: ${{ eq(parameters.deployInfra, true) }}
  - name: deployApp
    value: ${{ eq(parameters.deployApp, true) }}3
  

pool:
  name: Linux-sh-pool

stages:
  - stage: pre_steps
    displayName: Pre-steps
    jobs:
      - template: pre-steps.yaml # Reference the pre-steps jobs template

  - template: env.yaml
    parameters: 
      build_id: ${{parameters.build_id}}
      environments:
        # DigiGeld ACC
        - name: DigiGeld
          code: acc
          azureSubscription: DigiGeld SC ACC
          resource_group: dg-rg-acc
          location: northeurope
          acr_name: dgacracc
          cluster_name: dg-aks-acc
          dependsOn:
            - pre_steps # DigiGeld_acc depends on pre_steps

        # DigiGeld PROD
        - name: DigiGeld
          code: prod
          azureSubscription: DigiGeld SC PROD
          resource_group: dg-rg-prod1
          location: northeurope
          acr_name: dgacrprod1
          cluster_name: dg-aks-prod1
          dependsOn:
            - pre_steps
            - DigiGeld_acc # DigiGeld_prod depends on DigiGeld_acc
