apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  replicas: 1  # Updated for scalability
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: "CHANGE_IMAGE"
          ports:
            - containerPort: 2368
          env:
            - name: database__client
              value: mysql
            - name: database__connection__host
              value: mysql-service.ghost.svc.cluster.local
            - name: database__connection__user
              value: "root"
            - name: database__connection__password
              value: "CHANGE_PASSWORD"
            - name: database__connection__database
              value: ghost
            - name: url
              value: http://localhost:8080
          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-content
          persistentVolumeClaim:
            claimName: ghost-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost
spec:
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 2368
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet  # Changed from Deployment to StatefulSet for MySQL
metadata:
  name: mysql
  namespace: ghost
spec:
  replicas: 1  # Updated for high availability
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "CHANGE_PASSWORD"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ghost
spec:
  clusterIP: None  # Required for StatefulSet
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Increased storage for production use

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Increased storage for production database

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: ghost
spec:
  schedule: "0 2 * * *"  # Daily at 2:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:8.0
            command: ["/bin/bash", "-c"]
            args:
            - |
              mysqldump -h mysql-service.ghost -u root -p${MYSQL_ROOT_PASSWORD} ghost > /backup/ghost_backup.sql &&
              az storage blob upload --account-name <STORAGE_ACCOUNT> --container-name backups --file /backup/ghost_backup.sql --name ghost_backup_$(date +%F).sql
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            emptyDir: {}
